### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by amarabha** [ramsricharan/School-Diaries#1]
Dear Ramsricharan
thank you for this great application. I have one issue if you can help me to get the database schema that you use for classes and students. and are the application support more schools or just one school?

Best Regards,
Anas

**Comment by amarabha** [comment]
Dear Ram
I wait your reply on my previous issue.

Best Regards,

**Comment by ramsricharan** [comment]
> Dear Ram
> I wait your reply on my previous issue.
> 
> Best Regards,

Hello Anas,
Sorry for the delayed response. I used Firebase for this application. And the structure for my firebase real-time database is as follows. 
The current state of the application doesn't really save the school information.

# Overview
![image](https://user-images.githubusercontent.com/28557563/56604694-7356ce00-65b7-11e9-9eb2-dfbfe5d1b23d.png)

# Classes
![image](https://user-images.githubusercontent.com/28557563/56604855-c2046800-65b7-11e9-81c2-ef1fcdb2255f.png)

# Students
![image](https://user-images.githubusercontent.com/28557563/56604888-d34d7480-65b7-11e9-8abb-e902cfce7301.png)

# Teachers
![image](https://user-images.githubusercontent.com/28557563/56605045-1a3b6a00-65b8-11e9-9f09-e64fbd05da4f.png)

**Comment by ameer5565** [comment]
dear ram , 
i need your help in building my database , I admire your project and like to create updated version depanding on it , my data base is empty now , so some help is really appreciated .

**Comment by ramsricharan** [comment]
Hello Ameer,
Sure, let me know what I can do for you.

**Comment by ameer5565** [comment]
hello there bro ,
nice to be in contact with you,
am unable to assign teachers to any class , how to creat class to get class
code ?
am trying to copy past your database codes to mine to check if it will work
.
when press+ button i cannot add any class to teacher .
regards

**Comment by ameer5565** [comment]
ok after i added it manually , i got class in classes list , but then i
have another problem , or lets say these problems :-

1-how to add more classes via program not via web page of data base ?
2- how did you added the kids who already in the program ? to assign them
to the class.
appreciated

**Comment by ramsricharan** [comment]
Hello Ameer,
The reason why you are unable to assign classes to the teacher is because we did not give access for teachers to assign classes to themselves. Instead, our plan was to have an admin account which will be responsible to assign classes to the teachers. For now, the only way you can add a new class to a teacher is via the web. It was my final project so we did not have enough time to create the admin side of the app. Really sorry for the inconvenience.
2) To add the kids to the class, you need to click on the add child button in the children view and use the ChildID (eg: childid1).

**Comment by ameer5565** [comment]
am looking for a way to add children to the program , i mean adding
students to the project so you can add them to the classes .

adding classes via web is ok , as long as it is only a limited resource,
but adding kids must be done with the app , i appreciate it if you could
give me a link that i can follow to add a button that could upload kids
info from a an activity to firebase database .
thanks for your replay .

**Comment by ramsricharan** [comment]
You mean to create a new child and add to the class?

Well, even that is the responsibility of the admin side. Basically, any operation that will be handled by the school's admin department like creating new classes to the curriculum, joining students (creating new children), etc will be handled by the admin side of the app.

Everything that you can do with this app is shown in the video that I attached in my documentation. Here is the link to it in case you missed it.
https://www.youtube.com/watch?v=kkd5DLo274I&feature=youtu.be

**Comment by ameer5565** [comment]
i saw that video, but was thinking that i am missing somthin as i saw you
have kids + classes , but ya i need to add them to the app via web database
page , am looking to creat a page that allow teacher side to add classes +
kids , then i will consider it the admin , teachers dont need that app ,
admin and parents does need it , so if i upgrade the abilty to add children
and classes to the teacher side it will be an admin version , hope i can
pass with this .
thanks for your time my frind

**Comment by Hardijazaaziz** [comment]
Hello Ram ,,,
we have finale project graduate and we wanna developing your apps to contacting between **parent and teacher for  student our university** , we need your help in building the database ,because of our structure different that your project, we need firebase database to change it until possible with our projects , we admire your project and like to create updated version depending on it, so some help is really appreciated .


**thank for your helping us** 
email contact: hardi.jaza.htc@gmail.com
